# Generated by Django 6.0.4 on 2026-05-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='external_participants',
            field=models.JSONField(blank=True, default=list, verbose_name='External Participants'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online Meeting'),
        ),
        migrations.AddField(
            model_name='activity',
            name='meeting_provider',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Meeting Provider'),
        ),
        migrations.AddField(
            model_name='activity',
            name='meeting_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Meeting Link'),
        ),
        migrations.AddField(
            model_name='activity',
            name='reminder',
            field=models.CharField(blank=True, choices=[('', 'No Reminder'), ('5', '5 minutes before'), ('10', '10 minutes before'), ('15', '15 minutes before'), ('30', '30 minutes before'), ('60', '1 hour before'), ('1440', '1 day before')], max_length=10, null=True, verbose_name='Reminder'),
        ),
    ]
