# Generated by Django 6.0.4 on 2026-05-23 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_external_participants_activity_is_online_and_more'),
        ('mail', '0002_horillamail_bounced_at_horillamail_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_activities', to='mail.horillamailtemplate', verbose_name='Invitation Email Template'),
        ),
    ]
