# Generated by Django 6.0.4 on 2026-05-18 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewprocess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('model', 'company'), name='unique_active_review_process_per_model_company'),
        ),
    ]
