"""
Re-export Django core exceptions for Horilla platform code.
"""

from django.core.exceptions import (
    AppRegistryNotReady,
    BadRequest,
    DisallowedHost,
    DisallowedRedirect,
    EmptyResultSet,
    FieldDoesNotExist,
    FieldError,
    FullResultSet,
    ImproperlyConfigured,
    MiddlewareNotUsed,
    MultipleObjectsReturned,
    ObjectDoesNotExist,
    PermissionDenied,
    RequestAborted,
    RequestDataTooBig,
    SuspiciousFileOperation,
    SuspiciousMultipartForm,
    SuspiciousOperation,
    SynchronousOnlyOperation,
    TooManyFieldsSent,
    TooManyFilesSent,
    ValidationError,
    ViewDoesNotExist,
)

__all__ = [
    "AppRegistryNotReady",
    "BadRequest",
    "DisallowedHost",
    "DisallowedRedirect",
    "EmptyResultSet",
    "FieldDoesNotExist",
    "FieldError",
    "FullResultSet",
    "ImproperlyConfigured",
    "MiddlewareNotUsed",
    "MultipleObjectsReturned",
    "ObjectDoesNotExist",
    "PermissionDenied",
    "RequestAborted",
    "RequestDataTooBig",
    "SuspiciousFileOperation",
    "SuspiciousMultipartForm",
    "SuspiciousOperation",
    "SynchronousOnlyOperation",
    "TooManyFieldsSent",
    "TooManyFilesSent",
    "ValidationError",
    "ViewDoesNotExist",
]
