# Generated by Django 6.0.4 on 2026-05-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approvalrule",
            name="process_config",
        ),
    ]
