"""
URL configuration for Horilla Core app.
"""

# First party imports (Horilla)
from horilla.urls import include, path, re_path

# Local imports
from . import views

app_name = "core"
urlpatterns = [
    # Include API URLs
    re_path(r"^media/(?P<path>.*)$", views.protected_media, name="protected_media"),
    path("api/", include("horilla.contrib.core.api.urls")),
    path("", views.HomePageView.as_view(), name="home_view"),
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("active-tab/", views.SaveActiveTabView.as_view(), name="active_tab"),
    path("favicon.ico", views.FaviconRedirectView.as_view()),
    path("settings-view/", views.SettingView.as_view(), name="settings_view"),
    path("my-settings-view/", views.MySettingView.as_view(), name="my_settings_view"),
    path(
        "company-details-tab/",
        views.CompanyDetailsTab.as_view(),
        name="company_details_tab",
    ),
    path(
        "company-information/",
        views.CompanyInformationView.as_view(),
        name="company_information",
    ),
    path(
        "company-tab-view/",
        views.CompanyInformationTabView.as_view(),
        name="company_tab_view",
    ),
    path(
        "company-fiscal-year-tab/",
        views.CompanyFiscalYearTab.as_view(),
        name="company_fiscal_year_tab",
    ),
    path(
        "edit-company/<int:pk>/", views.CompanyFormView.as_view(), name="edit_company"
    ),
    path(
        "edit-company-multi-step/<int:pk>/",
        views.CompanyMultiFormView.as_view(),
        name="edit_company_multi_step",
    ),
    path("create-company/", views.CompanyFormView.as_view(), name="create_company"),
    path(
        "create-company-multi-step/",
        views.CompanyMultiFormView.as_view(),
        name="create_company_multi_step",
    ),
    path(
        "switch-company/<int:company_id>/",
        views.SwitchCompanyView.as_view(),
        name="switch_company",
    ),
    path(
        "toggle-all-companies/",
        views.ToggleAllCompaniesView.as_view(),
        name="toggle_all_companies",
    ),
    # Holiday Urls
    path(
        "holiday-list-view/", views.HolidayListView.as_view(), name="holiday_list_view"
    ),
    path("holiday-view/", views.HolidayView.as_view(), name="holiday_view"),
    path(
        "holiday-create-form/",
        views.HolidayFormView.as_view(),
        name="holiday_create_form",
    ),
    path(
        "holiday-update-form/<int:pk>/",
        views.HolidayFormView.as_view(),
        name="holiday_update_form",
    ),
    path(
        "holiday-delete-view/<int:pk>/",
        views.HolidayDeleteView.as_view(),
        name="holiday_delete_view",
    ),
    path(
        "holiday-detail-view/<int:pk>/",
        views.HolidayDetailView.as_view(),
        name="holiday_detail_view",
    ),
    # Fiscal Year Urls
    path(
        "fiscal-year-form/",
        views.FiscalYearFormView.as_view(),
        name="fiscal_year_form",
    ),
    path(
        "fiscal-year-form/<int:pk>/",
        views.FiscalYearFormView.as_view(),
        name="fiscal_year_form_edit",
    ),
    path(
        "fiscal-year-fields/",
        views.FiscalYearFieldsView.as_view(),
        name="fiscal_year_fields",
    ),
    path(
        "fiscal-year-calendar-preview/",
        views.FiscalYearCalendarPreviewView.as_view(),
        name="fiscal_year_calendar_preview",
    ),
    path(
        "fiscal-year-calendar/<int:pk>/",
        views.FiscalYearCalendarView.as_view(),
        name="fiscal_year_calendar",
    ),
    path(
        "calculate-week-start-day/",
        views.CalculateWeekStartDayView.as_view(),
        name="calculate_week_start_day",
    ),
    # Multiple Currency Urls
    path(
        "multiple-currency/",
        views.CompanyMultipleCurrency.as_view(),
        name="multiple_currency",
    ),
    path(
        "currency-list-view/",
        views.CurrencyListView.as_view(),
        name="currency_list_view",
    ),
    path(
        "change-default-currency/<int:pk>/",
        views.ChangeDefaultCurrencyView.as_view(),
        name="change_default_currency",
    ),
    path(
        "add-currency/",
        views.AddCurrencyView.as_view(),
        name="add_currency",
    ),
    path(
        "fetch-exchange-rate/",
        views.FetchExchangeRateView.as_view(),
        name="fetch_exchange_rate",
    ),
    path(
        "edit-currency/<int:pk>/",
        views.AddCurrencyView.as_view(),
        name="edit_currency",
    ),
    path(
        "change-default-currency-form/",
        views.ChangeDefaultCurrencyFormView.as_view(),
        name="change_default_currency_view",
    ),
    path(
        "change-conversion-rate-view/",
        views.ConversionRateFormView.as_view(),
        name="conversion_rate_view",
    ),
    path(
        "dated-conversion-rates/",
        views.DatedConversionRateFormView.as_view(),
        name="dated_conversion_rate_view",
    ),
    path(
        "dated-currency-list-view/",
        views.DatedCurrencyListView.as_view(),
        name="dated_currency_list_view",
    ),
    path(
        "delete-currency/<int:pk>/",
        views.CurrencyDeleteView.as_view(),
        name="delete_currency",
    ),
    # Business Hour urls
    path(
        "business-hour-view/",
        views.BusinessHourView.as_view(),
        name="business_hour_view",
    ),
    path(
        "business-hour-card/",
        views.BusinessHourCardView.as_view(),
        name="business_hour_card_view",
    ),
    path(
        "business-hour-create-form/",
        views.BusinessHourFormView.as_view(),
        name="business_hour_create_form",
    ),
    path(
        "business-hour-update-form/<int:pk>/",
        views.BusinessHourFormView.as_view(),
        name="business_hour_update_form",
    ),
    path(
        "business-hour/<int:pk>/holidays/",
        views.BusinessHourHolidayPanelView.as_view(),
        name="business_hour_holiday_panel",
    ),
    path(
        "business-hour/<int:pk>/holiday-list-view/",
        views.BusinessHourHolidayListView.as_view(),
        name="business_hour_holiday_list_view",
    ),
    path(
        "business-hour/<int:pk>/holiday-modal/",
        views.BusinessHourHolidayModalView.as_view(),
        name="business_hour_holiday_modal",
    ),
    path(
        "business-hour/<int:pk>/holidays/<int:holiday_pk>/toggle/",
        views.BusinessHourHolidayToggleView.as_view(),
        name="business_hour_holiday_toggle",
    ),
    path(
        "business-hour/<int:pk>/holidays/add/",
        views.BusinessHourAddHolidayView.as_view(),
        name="business_hour_add_holiday",
    ),
    path(
        "business-hour/<int:pk>/holidays/<int:holiday_pk>/remove/",
        views.BusinessHourHolidayRemoveView.as_view(),
        name="business_hour_holiday_remove",
    ),
    path(
        "business-hour-holiday-readonly-detail/<int:pk>/",
        views.BusinessHourHolidayReadonlyDetailView.as_view(),
        name="business_hour_holiday_readonly_detail",
    ),
    # Shift hour urls
    path(
        "shift-hour-list-view/",
        views.ShiftHourListView.as_view(),
        name="shift_hour_list_view",
    ),
    path(
        "shift-hour-create-form/",
        views.ShiftHourFormView.as_view(),
        name="shift_hour_create_form",
    ),
    path(
        "shift-hour-update-form/<int:pk>/",
        views.ShiftHourFormView.as_view(),
        name="shift_hour_update_form",
    ),
    path(
        "shift-hour-delete-view/<int:pk>/",
        views.ShiftHourDeleteView.as_view(),
        name="shift_hour_delete_view",
    ),
    path(
        "shift-hour-detail-view/<int:pk>/",
        views.ShiftHourDetailView.as_view(),
        name="shift_hour_detail_view",
    ),
    # User urls
    path("user-view/", views.UserView.as_view(), name="user_view"),
    path("user-nav-view/", views.UserNavbar.as_view(), name="user_nav_view"),
    path("user-list-view/", views.UserListView.as_view(), name="user_list_view"),
    path(
        "user-kanban-view/",
        views.UserKanbanView.as_view(),
        name="user_kanban_view",
    ),
    path(
        "user-group-by-view/",
        views.UserGroupByView.as_view(),
        name="user_group_by_view",
    ),
    path("user-create-form/", views.UserFormView.as_view(), name="user_create_form"),
    path(
        "user-edit-form/<int:pk>/",
        views.UserFormView.as_view(),
        name="user_edit_form",
    ),
    path(
        "user-create-single-form/",
        views.UserFormViewSingle.as_view(),
        name="user_create_single_form",
    ),
    path(
        "user-edit-single-form/<int:pk>/",
        views.UserFormViewSingle.as_view(),
        name="user_edit_single_form",
    ),
    path(
        "user-change-company-form/<int:pk>/",
        views.ChangeUserCompanyView.as_view(),
        name="user_change_company_form",
    ),
    path(
        "get-company-related-fields/",
        views.GetCompanyRelatedFieldsView.as_view(),
        name="get_company_related_fields",
    ),
    path(
        "user-delete-view/<int:pk>/",
        views.UserDeleteView.as_view(),
        name="user_delete_view",
    ),
    path(
        "user-detail-view/<int:pk>/",
        views.UserDetailView.as_view(),
        name="user_detail_view",
    ),
    path(
        "my-profile-view/",
        views.MyProfileView.as_view(),
        name="my_profile_view",
    ),
    path(
        "login-history-list/",
        views.LoginHistoryListView.as_view(),
        name="login_history_list",
    ),
    path(
        "login-history-navbar/",
        views.LoginHistoryNavbar.as_view(),
        name="login_history_navbar",
    ),
    path(
        "login-history-view/",
        views.LoginHistoryView.as_view(),
        name="login_history_view",
    ),
    path(
        "get-country-subdivisions/",
        views.GetCountrySubdivisionsView.as_view(),
        name="get_country_subdivisions",
    ),
    # role urls
    path("roles-view/", views.RolesView.as_view(), name="roles_view"),
    path("roles-nav-bar/", views.RoleNavbar.as_view(), name="roles_nav_bar"),
    path(
        "roles-hierarchy-view/",
        views.RolesHierarchyView.as_view(),
        name="roles_hierarchy_view",
    ),
    path("roles-list-view/", views.RoleListView.as_view(), name="role_list_view"),
    path("create-roles-view/", views.AddRole.as_view(), name="create_roles_view"),
    path(
        "edit-roles-view/<int:pk>/",
        views.AddRole.as_view(),
        name="edit_roles_view",
    ),
    path(
        "add-user-to-roles-view/",
        views.AddUserToRole.as_view(),
        name="add_user_to_roles_view",
    ),
    path(
        "delete-user-from-role/<int:pk>/",
        views.DeleteUserFromRole.as_view(),
        name="delete_user_from_role",
    ),
    path(
        "delete-role/<int:pk>/",
        views.RoleDeleteView.as_view(),
        name="delete_role",
    ),
    path(
        "view-user-in-role/",
        views.UsersInRoleView.as_view(),
        name="view_user_in_role",
    ),
    path(
        "view-user-in-role-list-view/",
        views.RoleUsersListView.as_view(),
        name="view_user_in_role_list_view",
    ),
    path(
        "view-user-in-role-nav-view/",
        views.RoleUsersNavView.as_view(),
        name="view_user_in_role_nav_view",
    ),
    # branches urls
    path("branches-view/", views.BranchesView.as_view(), name="branches_view"),
    path(
        "branches-nav-view/",
        views.BranchNavbar.as_view(),
        name="branches_nav_view",
    ),
    path(
        "branches-list-view/",
        views.BranchListView.as_view(),
        name="branches_list_view",
    ),
    path(
        "branch-detail-view/<int:pk>/",
        views.BranchDetailView.as_view(),
        name="branch_detail_view",
    ),
    path(
        "branch-delete/<int:pk>/",
        views.BranchDeleteView.as_view(),
        name="branch_delete",
    ),
    # Department urls
    path(
        "department-view/",
        views.DepartmentView.as_view(),
        name="department_view",
    ),
    path(
        "department-nav-view/",
        views.DepartmentNavbar.as_view(),
        name="department_nav_view",
    ),
    path(
        "department-list-view/",
        views.DepartmentListView.as_view(),
        name="department_list_view",
    ),
    path(
        "department-create-form/",
        views.DepartmentFormView.as_view(),
        name="department_create_form",
    ),
    path(
        "department-update-form/<int:pk>/",
        views.DepartmentFormView.as_view(),
        name="department_update_form",
    ),
    path(
        "department-delete-view/<int:pk>/",
        views.DepartmentDeleteView.as_view(),
        name="department_delete_view",
    ),
    # Team role urls
    path("team-role-view/", views.TeamRoleView.as_view(), name="team_role_view"),
    path(
        "team-role-nav-view/",
        views.TeamRoleNavbar.as_view(),
        name="team_role_nav_view",
    ),
    path(
        "team-role-list-view/",
        views.TeamRoleListView.as_view(),
        name="team_role_list_view",
    ),
    path(
        "team-role-create-form/",
        views.TeamRoleFormView.as_view(),
        name="team_role_create_form",
    ),
    path(
        "team-role-update-form/<int:pk>/",
        views.TeamRoleFormView.as_view(),
        name="team_role_update_form",
    ),
    path(
        "team-role-delete-view/<int:pk>/",
        views.TeamRoleDeleteView.as_view(),
        name="team_role_delete_view",
    ),
    # Customer role urls
    path(
        "customer-role-view/",
        views.CustomerRoleView.as_view(),
        name="customer_role_view",
    ),
    path(
        "customer-role-nav-view/",
        views.CustomerRoleNavbar.as_view(),
        name="customer_role_nav_view",
    ),
    path(
        "customer-role-list-view/",
        views.CustomerRoleListView.as_view(),
        name="customer_role_list_view",
    ),
    path(
        "customer-role-create-form/",
        views.CustomerRoleFormView.as_view(),
        name="customer_role_create_form",
    ),
    path(
        "customer-role-update-form/<int:pk>/",
        views.CustomerRoleFormView.as_view(),
        name="customer_role_update_form",
    ),
    path(
        "customer-role-delete-view/<int:pk>/",
        views.CustomerRoleDeleteView.as_view(),
        name="customer_role_delete_view",
    ),
    # Partner role urls
    path(
        "partner-role-view/",
        views.PartnerRoleView.as_view(),
        name="partner_role_view",
    ),
    path(
        "partner-role-nav-view/",
        views.PartnerRoleNavbar.as_view(),
        name="partner_role_nav_view",
    ),
    path(
        "partner-role-list-view/",
        views.PartnerRoleListView.as_view(),
        name="partner_role_list_view",
    ),
    path(
        "partner-role-create-form/",
        views.PartnerRoleFormView.as_view(),
        name="partner_role_create_form",
    ),
    path(
        "partner-role-update-form/<int:pk>/",
        views.PartnerRoleFormView.as_view(),
        name="partner_role_update_form",
    ),
    path(
        "partner-role-delete-view/<int:pk>/",
        views.PartnerRoleDeleteView.as_view(),
        name="partner_role_delete_view",
    ),
    # Recyclebin urls
    path(
        "recycle-bin-view/",
        views.RecycleBinView.as_view(),
        name="recycle_bin_view",
    ),
    path(
        "recycle-bin-navbar/",
        views.RecycleBinNavbar.as_view(),
        name="recycle_bin_navbar",
    ),
    path(
        "recycle-bin-list-view/",
        views.RecycleBinListView.as_view(),
        name="recycle_bin_list_view",
    ),
    path(
        "recycle-bin-delete/<int:pk>/",
        views.RecycleDeleteView.as_view(),
        name="recycle_bin_delete",
    ),
    path(
        "recycle-bin-restore/<int:pk>/",
        views.RecycleRestoreView.as_view(),
        name="recycle_bin_restore",
    ),
    path(
        "recycle-bin-empty/",
        views.EmptyRecycleBinView.as_view(),
        name="recycle_bin_empty",
    ),
    path(
        "bulk-recycle-bin-restore/",
        views.BulkRestoreRecycleView.as_view(),
        name="bulk_recycle_bin_restore",
    ),
    path(
        "bulk-recycle-bin-delete/",
        views.BulkDeleteRecycleBinView.as_view(),
        name="bulk_recycle_bin_delete",
    ),
    path(
        "recycle-bin-policy-view/",
        views.BinPolicyView.as_view(),
        name="recycle_bin_policy_view",
    ),
    # my settings holidays urls
    path(
        "user-holiday-view/",
        views.UserHolidayView.as_view(),
        name="user_holiday_view",
    ),
    path(
        "user-holiday-nav/",
        views.UserHolidayNavbar.as_view(),
        name="user_holiday_nav",
    ),
    path(
        "user-holiday-list/",
        views.UserHolidayListView.as_view(),
        name="user_holiday_list",
    ),
    path(
        "user-holiday-detail/<int:pk>/",
        views.UserHolidayDetailView.as_view(),
        name="user_holiday_detail",
    ),
    # my settings user login history urls
    path(
        "user-login-history-view/",
        views.UserLoginHistoryView.as_view(),
        name="user_login_history_view",
    ),
    path(
        "user-login-history-nav/",
        views.UserLoginHistoryNavbar.as_view(),
        name="user_login_history_nav",
    ),
    path(
        "user-login-history-list/",
        views.UserloginHistoryListView.as_view(),
        name="user_login_history_list",
    ),
    # Regional Formating urls
    path(
        "regional-formating-view/",
        views.ReginalFormatingView.as_view(),
        name="regional_formating_view",
    ),
    path("reload-messages/", views.ReloadMessages.as_view(), name="reload_messages"),
    path("import-view/", views.ImportView.as_view(), name="import_view"),
    path("import-tab-view/", views.ImportTabView.as_view(), name="import_tab_view"),
    path("import-data/", views.ImportDataView.as_view(), name="import_data"),
    path("step1/", views.ImportStep1View.as_view(), name="import_step1"),
    path("step2/", views.ImportStep2View.as_view(), name="import_step2"),
    path("step3/", views.ImportStep3View.as_view(), name="import_step3"),
    path("step4/", views.ImportStep4View.as_view(), name="import_step4"),
    path("get-fields/", views.GetModelFieldsView.as_view(), name="get_model_fields"),
    path(
        "get-unique-values/",
        views.GetUniqueValuesView.as_view(),
        name="get_unique_values",
    ),
    path(
        "update-field-status/",
        views.UpdateFieldStatusView.as_view(),
        name="update_field_status",
    ),
    path(
        "update-value-mapping-status/",
        views.UpdateValueMappingStatusView.as_view(),
        name="update_value_mapping_status",
    ),
    path(
        "download-errors/",
        views.DownloadErrorFileView.as_view(),
        name="download_error_file",
    ),
    path(
        "download-imported-file/",
        views.DownloadImportedFileView.as_view(),
        name="download_imported_file",
    ),
    path(
        "download-template-modal/",
        views.DownloadTemplateModalView.as_view(),
        name="download_template_modal",
    ),
    path(
        "download-template/",
        views.DownloadTemplateView.as_view(),
        name="download_template",
    ),
    path(
        "import-history-view/",
        views.ImportHistoryView.as_view(),
        name="import_history_view",
    ),
    # Permission urls
    path(
        "role-permission-view/",
        views.RolePermissionView.as_view(),
        name="role_permission_view",
    ),
    path(
        "role-permission-tab/",
        views.RolePermissionTabView.as_view(),
        name="role_permission_tab",
    ),
    path("role-tab/", views.GroupTab.as_view(), name="role_tab"),
    path(
        "permission-tab/",
        views.PermissionTab.as_view(),
        name="permission_tab",
    ),
    path(
        "roles-permissions/<int:role_id>/",
        views.RolePermissionsView.as_view(),
        name="role_permissions_view",
    ),
    path(
        "role-members/<int:role_id>/",
        views.RoleMembersView.as_view(),
        name="role_members_view",
    ),
    path(
        "roles-update-permissions/<int:role_id>/",
        views.UpdateRolePermissionsView.as_view(),
        name="update_role_permissions",
    ),
    path(
        "load-more-users/",
        views.LoadMoreUsersView.as_view(),
        name="load_more_users",
    ),
    path(
        "load-user-permissions/<int:user_id>/",
        views.LoadUserPermissionsView.as_view(),
        name="load_user_permissions",
    ),
    path(
        "assign-users-perm/",
        views.AssignUsersView.as_view(),
        name="assign_users_perm",
    ),
    path(
        "update-user-permissions/<int:user_id>/",
        views.UpdateUserPermissionsView.as_view(),
        name="update_user_permissions",
    ),
    path(
        "update-role-model-permissions/<int:role_id>/",
        views.UpdateRoleModelPermissionsView.as_view(),
        name="update_role_model_permissions",
    ),
    path(
        "role-permissions-all/<int:role_id>/",
        views.UpdateRoleAllPermissionsView.as_view(),
        name="update_role_all_permissions",
    ),
    path(
        "user-update-model-permissions/<int:user_id>/",
        views.UpdateUserModelPermissionsView.as_view(),
        name="update_user_model_permissions",
    ),
    path(
        "user-update-all-permissions/<int:user_id>/",
        views.UpdateUserAllPermissionsView.as_view(),
        name="update_user_all_permissions",
    ),
    path(
        "bulk-update-user-model-permissions/",
        views.BulkUpdateUserModelPermissionsView.as_view(),
        name="bulk_update_user_model_permissions",
    ),
    path(
        "bulk-update-user-all-permissions/",
        views.BulkUpdateUserAllPermissionsView.as_view(),
        name="bulk_update_user_all_permissions",
    ),
    path(
        "super-user-tab/",
        views.SuperUserView.as_view(),
        name="super_user_tab",
    ),
    path(
        "super-user-nav-bar/",
        views.SuperUserNavbar.as_view(),
        name="super_user_nav_bar",
    ),
    path(
        "super-user-list/",
        views.SuperUserTab.as_view(),
        name="super_user_list",
    ),
    path(
        "super-user-status/<int:pk>/",
        views.ToggleSuperuserView.as_view(),
        name="super_user_status",
    ),
    path(
        "add-super-users/",
        views.AddSuperUsersView.as_view(),
        name="add_super_users",
    ),
    path(
        "search-role-models/<int:role_id>/",
        views.SearchRoleModelsView.as_view(),
        name="search_role_models",
    ),
    path(
        "search-user-models/<int:user_id>/",
        views.SearchUserModelsView.as_view(),
        name="search_user_models",
    ),
    path(
        "search-assign-models/",
        views.SearchAssignModelsView.as_view(),
        name="search_assign_models",
    ),
    path(
        "model-fields-modal-role/<int:role_id>/<str:app_label>/<str:model_name>/",
        views.ModelFieldsModalView.as_view(),
        name="model_fields_modal_role",
    ),
    path(
        "model-fields-modal-user/<int:user_id>/<str:app_label>/<str:model_name>/",
        views.ModelFieldsModalView.as_view(),
        name="model_fields_modal_user",
    ),
    path(
        "model-fields-modal-bulk/<str:app_label>/<str:model_name>/",
        views.ModelFieldsModalView.as_view(),
        name="model_fields_modal_bulk",
    ),
    path(
        "update-field-permission-role/<int:role_id>/<str:app_label>/<str:model_name>/<str:field_name>/",
        views.UpdateFieldPermissionView.as_view(),
        name="update_field_permission_role",
    ),
    path(
        "update-field-permission-user/<int:user_id>/<str:app_label>/<str:model_name>/<str:field_name>/",
        views.UpdateFieldPermissionView.as_view(),
        name="update_field_permission_user",
    ),
    path(
        "save-all-field-permissions-role/<int:role_id>/",
        views.SaveAllFieldPermissionsView.as_view(),
        name="save_all_field_permissions_role",
    ),
    path(
        "save-all-field-permissions-user/<int:user_id>/",
        views.SaveAllFieldPermissionsView.as_view(),
        name="save_all_field_permissions_user",
    ),
    path(
        "save-bulk-field-permissions/",
        views.SaveBulkFieldPermissionsView.as_view(),
        name="save_bulk_field_permissions",
    ),
    # Initialize database urls
    path(
        "initialize-database/",
        views.InitializeDatabase.as_view(),
        name="initialize_database",
    ),
    path(
        "initialize-database-user/",
        views.InitializeDatabaseUser.as_view(),
        name="initialize_database_user",
    ),
    path(
        "initialize-database-role/",
        views.InitializeRoleView.as_view(),
        name="initialize_database_role",
    ),
    path(
        "initialize-database-company/",
        views.InitializeDatabaseCompany.as_view(),
        name="initialize_database_company",
    ),
    path(
        "sign-up-user/",
        views.SignUpFormView.as_view(),
        name="sign_up_user",
    ),
    path(
        "initialize-company-form/",
        views.InitializeCompanyFormView.as_view(),
        name="initialize_company_form",
    ),
    path(
        "forgot-password/", views.ForgotPasswordView.as_view(), name="forgot_password"
    ),
    path(
        "reset-password/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "change-password-view/",
        views.ChangePasswordView.as_view(),
        name="change_password_view",
    ),
    path(
        "change-password-form/",
        views.ChangePasswordFormView.as_view(),
        name="change_password_form",
    ),
    # Load Data
    path("load-data/", views.LoadDatabase.as_view(), name="load_data"),
    path("load-demo-data/", views.LoadDemoDatabase.as_view(), name="load_demo_data"),
    path(
        "configure-demo-data/",
        views.ConfigureDemoData.as_view(),
        name="configure_demo_data",
    ),
    # Export
    path("export-view/", views.ExportView.as_view(), name="export_view"),
    path(
        "schedule-modal/",
        views.ExportScheduleModalView.as_view(),
        name="schedule_modal",
    ),
    path(
        "schedule-create/",
        views.ExportScheduleCreateView.as_view(),
        name="schedule_create",
    ),
    path(
        "schedule-export-list/",
        views.ScheduleExportListView.as_view(),
        name="schedule_export_list",
    ),
    path(
        "schedule-export-delete/<int:pk>/",
        views.ScheduleExportDeleteView.as_view(),
        name="schedule_export_delete",
    ),
    path(
        "schedule-export-detail-view/<int:pk>/",
        views.ScheduleExportDetailView.as_view(),
        name="schedule_export_detail_view",
    ),
    # Version info urls
    path(
        "version-info-view/",
        views.VersionInfotemplateView.as_view(),
        name="version_info_view",
    ),
]
