"""
Defines URL patterns for the Activity app, mapping various activity-related views
such as list, detail, create, update, delete, and Kanban views to their respective endpoints.
"""

# First party imports (Horilla)
from horilla.urls import path

# Local imports
from . import views

app_name = "activity"

urlpatterns = [
    path("activity-view/", views.ActivityView.as_view(), name="activity_view"),
    path(
        "activity-tabbed-view/",
        views.AllActivityTabbedView.as_view(),
        name="activity_tabbed_view",
    ),
    path(
        "activity-list-view/",
        views.AllActivityListView.as_view(),
        name="activity_list_view",
    ),
    path(
        "global-task-list/",
        views.GlobalTaskListView.as_view(),
        name="global_task_list",
    ),
    path(
        "global-meeting-list/",
        views.GlobalMeetingListView.as_view(),
        name="global_meeting_list",
    ),
    path(
        "global-call-list/",
        views.GlobalCallListView.as_view(),
        name="global_call_list",
    ),
    path(
        "global-event-list/",
        views.GlobalEventListView.as_view(),
        name="global_event_list",
    ),
    path(
        "activity-nav-view/", views.ActivityNavbar.as_view(), name="activity_nav_view"
    ),
    path(
        "activity-kanban-view/",
        views.AcivityKanbanView.as_view(),
        name="activity_kanban_view",
    ),
    path(
        "activity-kanban-tabbed-view/",
        views.AllActivityKanbanTabbedView.as_view(),
        name="activity_kanban_tabbed_view",
    ),
    path(
        "global-task-kanban/",
        views.GlobalTaskKanbanView.as_view(),
        name="global_task_kanban",
    ),
    path(
        "global-meeting-kanban/",
        views.GlobalMeetingKanbanView.as_view(),
        name="global_meeting_kanban",
    ),
    path(
        "global-call-kanban/",
        views.GlobalCallKanbanView.as_view(),
        name="global_call_kanban",
    ),
    path(
        "global-event-kanban/",
        views.GlobalEventKanbanView.as_view(),
        name="global_event_kanban",
    ),
    path("task-create-form/", views.TaskCreateForm.as_view(), name="task_create_form"),
    path(
        "task-update-form/<int:pk>/",
        views.TaskCreateForm.as_view(),
        name="task_update_form",
    ),
    path(
        "meeting-create-form/",
        views.MeetingsCreateForm.as_view(),
        name="meeting_create_form",
    ),
    path(
        "meeting-update-form/<int:pk>/",
        views.MeetingsCreateForm.as_view(),
        name="meeting_update_form",
    ),
    path(
        "call-create-form/",
        views.CallCreateForm.as_view(),
        name="call_create_form",
    ),
    path(
        "call-update-form/<int:pk>/",
        views.CallCreateForm.as_view(),
        name="call_update_form",
    ),
    path(
        "event-create-form/",
        views.EventCreateForm.as_view(),
        name="event_create_form",
    ),
    path(
        "event-update-form/<int:pk>/",
        views.EventCreateForm.as_view(),
        name="event_update_form",
    ),
    path(
        "tasks/<int:object_id>/",
        views.TaskListView.as_view(),
        name="task_list",
    ),
    path(
        "meetings/<int:object_id>/",
        views.MeetingListView.as_view(),
        name="meeting_list",
    ),
    path(
        "calls/<int:object_id>/",
        views.CallListView.as_view(),
        name="call_list",
    ),
    path(
        "emails/<int:object_id>/",
        views.EmailListView.as_view(),
        name="email_list",
    ),
    path(
        "events/<int:object_id>/",
        views.EventListView.as_view(),
        name="event_list",
    ),
    path(
        "delete-activity/<int:pk>/",
        views.ActivityDeleteView.as_view(),
        name="delete_activity",
    ),
    path(
        "activity-create-form/",
        views.ActivityCreateView.as_view(),
        name="activity_create_form",
    ),
    path(
        "activity-edit-form/<int:pk>/",
        views.ActivityCreateView.as_view(),
        name="activity_edit_form",
    ),
    path(
        "activity-detail/<int:pk>/",
        views.ActivityDetailView.as_view(),
        name="activity_detail",
    ),
    path(
        "activity-details-tab/<int:pk>/",
        views.ActivityDetailTab.as_view(),
        name="activity_details_tab",
    ),
    path(
        "activity-detail-view-tabs/",
        views.ActivityDetailViewTabView.as_view(),
        name="activity_detail_view_tabs",
    ),
    path(
        "activity-status-update/<int:pk>/",
        views.ActivityStatusUpdateView.as_view(),
        name="activity_status_update",
    ),
    path(
        "activity-history-tab-view/<int:pk>/",
        views.ActivityHistoryTabView.as_view(),
        name="activity_history_tab_view",
    ),
    path(
        "activity-notes-attachments/<int:pk>/",
        views.ActivitynNotesAndAttachments.as_view(),
        name="activity_notes_attachments",
    ),
    path(
        "meeting/add-email/",
        views.MeetingAddEmailView.as_view(),
        name="meeting_add_email",
    ),
    path(
        "meeting/remove-email/",
        views.MeetingRemoveEmailView.as_view(),
        name="meeting_remove_email",
    ),
]
