# Generated by Django 6.0.4 on 2026-05-23 09:03

import django.db.models.deletion
import horilla.registry.limiters
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_businesshour_options_businesshour_holidays_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Rule Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('trigger_on_create', models.BooleanField(default=True, help_text='Run this workflow when a new record is created.', verbose_name='When record is created')),
                ('trigger_on_edit', models.BooleanField(default=False, help_text='Run this workflow when an existing record is edited.', verbose_name='When record is edited')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('model', models.ForeignKey(help_text='The module (record type) this rule applies to.', limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('workflow_models'), on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rules', to='core.horillacontenttype', verbose_name='Module')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Workflow Rule',
                'verbose_name_plural': 'Workflow Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('exact', 'Equals'), ('ne', 'Not Equals'), ('icontains', 'Contains'), ('not_contains', 'Does Not Contain'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('isnull', 'Is Empty'), ('isnotnull', 'Is Not Empty'), ('between', 'Between')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3, verbose_name='Logical Operator')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='workflow.workflowrule', verbose_name='Workflow Rule')),
            ],
            options={
                'verbose_name': 'Workflow Condition',
                'verbose_name_plural': 'Workflow Conditions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('action_type', models.CharField(choices=[('update_field', 'Update Field'), ('assign_task', 'Assign Task'), ('email', 'Email'), ('notification', 'Notification')], max_length=20, verbose_name='Action')),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='Type-specific configuration. update_field: {field, value}. assign_task: {subject, due_days, priority, owner_id}. email: {template_id, to}. notification: {message, user_ids}.')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow.workflowrule', verbose_name='Workflow Rule')),
            ],
            options={
                'verbose_name': 'Workflow Action',
                'verbose_name_plural': 'Workflow Actions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTimeTriggerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('delay_value', models.PositiveIntegerField(default=1, verbose_name='Delay')),
                ('delay_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='days', max_length=10, verbose_name='Unit')),
                ('delay_direction', models.CharField(choices=[('after', 'After'), ('before', 'Before')], default='after', max_length=10, verbose_name='Direction')),
                ('trigger_date_field', models.CharField(help_text="Use 'rule_trigger_date' to fire relative to when the rule triggered, or enter a date field name from the target model.", max_length=100, verbose_name='Trigger Date')),
                ('action_type', models.CharField(choices=[('update_field', 'Update Field'), ('assign_task', 'Assign Task'), ('email', 'Email'), ('notification', 'Notification')], max_length=20, verbose_name='Action Type')),
                ('action_config', models.JSONField(blank=True, default=dict, verbose_name='Action Config')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_trigger_actions', to='workflow.workflowrule', verbose_name='Workflow Rule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Workflow Time Trigger Action',
                'verbose_name_plural': 'Workflow Time Trigger Actions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledWorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('object_id', models.PositiveIntegerField(verbose_name='Record ID')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='Scheduled At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Executed At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('time_trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_executions', to='workflow.workflowtimetriggeraction', verbose_name='Time Trigger')),
            ],
            options={
                'verbose_name': 'Scheduled Workflow Execution',
                'verbose_name_plural': 'Scheduled Workflow Executions',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='workflow_sc_status_65e1ef_idx')],
            },
        ),
    ]
