# Generated by Django 6.0.4 on 2026-05-23 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0004_activity_mail_template'),
        ('core', '0002_alter_businesshour_options_businesshour_holidays_and_more'),
        ('mail', '0002_horillamail_bounced_at_horillamail_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(help_text='Unique URL identifier for the booking page.', max_length=100, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Duration (minutes)')),
                ('is_online', models.BooleanField(default=True, verbose_name='Online Meeting')),
                ('meeting_provider', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('ms_teams', 'Microsoft Teams')], help_text='Required when Online Meeting is enabled.', max_length=20, verbose_name='Meeting Provider')),
                ('location', models.CharField(blank=True, help_text='Physical address for in-person meetings.', max_length=255, verbose_name='Location')),
                ('buffer_before', models.PositiveIntegerField(default=0, verbose_name='Buffer Before (minutes)')),
                ('buffer_after', models.PositiveIntegerField(default=0, verbose_name='Buffer After (minutes)')),
                ('max_per_day', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited.', null=True, verbose_name='Max Bookings Per Day')),
                ('advance_notice', models.PositiveIntegerField(default=60, help_text='Minimum notice required before a booking can be made.', verbose_name='Advance Notice (minutes)')),
                ('booking_window', models.PositiveIntegerField(default=30, help_text='How many days into the future visitors can book.', verbose_name='Booking Window (days)')),
                ('questions', models.JSONField(blank=True, default=list, help_text='List of questions to ask the booker.', verbose_name='Custom Questions')),
                ('reminder_hours', models.PositiveIntegerField(blank=True, help_text='Send reminder email X hours before the meeting. Leave blank to disable.', null=True, verbose_name='Reminder (hours before)')),
                ('allow_reschedule', models.BooleanField(default=True, verbose_name='Allow Rescheduling')),
                ('reschedule_cutoff_days', models.PositiveIntegerField(default=1, help_text='Prevent rescheduling if less than X days before the meeting.', verbose_name='Reschedule Cutoff (days)')),
                ('allow_cancel', models.BooleanField(default=True, verbose_name='Allow Cancellation')),
                ('cancel_cutoff_days', models.PositiveIntegerField(default=1, help_text='Prevent cancellation if less than X days before the meeting.', verbose_name='Cancel Cutoff (days)')),
                ('primary_color', models.CharField(default='#e54f38', help_text='Hex color used on the public booking page (e.g. #e54f38).', max_length=7, verbose_name='Brand Color')),
                ('business_hour', models.ForeignKey(blank=True, help_text='Company business hours that govern available booking slots.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_pages', to='core.businesshour', verbose_name='Business Hour')),
                ('cancellation_mail_template', models.ForeignKey(blank=True, help_text='Optional. Overrides the default cancellation email design.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_cancellation_pages', to='mail.horillamailtemplate', verbose_name='Cancellation Email Template')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('confirmation_mail_template', models.ForeignKey(blank=True, help_text='Optional. Overrides the default confirmation email design.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_confirmation_pages', to='mail.horillamailtemplate', verbose_name='Confirmation Email Template')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_pages', to=settings.AUTH_USER_MODEL, verbose_name='Host')),
                ('participants', models.ManyToManyField(blank=True, help_text='Users who will be added as participants to every meeting booked via this page.', related_name='participant_booking_pages', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
                ('reschedule_mail_template', models.ForeignKey(blank=True, help_text='Optional. Overrides the default reschedule email design.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_reschedule_pages', to='mail.horillamailtemplate', verbose_name='Reschedule Email Template')),
                ('shift_hour', models.ForeignKey(blank=True, help_text='Use shift hours schedule for slot availability instead of business hours.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_pages', to='core.shifthour', verbose_name='Shift Hours')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Booking Page',
                'verbose_name_plural': 'Booking Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('booker_name', models.CharField(max_length=200, verbose_name='Booker Name')),
                ('booker_email', models.EmailField(max_length=254, verbose_name='Booker Email')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end_datetime', models.DateTimeField(verbose_name='End Date & Time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20, verbose_name='Status')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Question Answers')),
                ('meeting_url', models.URLField(blank=True, verbose_name='Meeting URL')),
                ('cancellation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Cancellation Token')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation Reason')),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='activity.activity', verbose_name='Meeting Activity')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('booking_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.bookingpage', verbose_name='Booking Page')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['booking_page', 'start_datetime'], name='booking_boo_booking_ed0f51_idx'), models.Index(fields=['booker_email'], name='booking_boo_booker__b3d5bd_idx'), models.Index(fields=['status'], name='booking_boo_status_e01616_idx')],
            },
        ),
    ]
