# Generated by Django 6.0.4 on 2026-05-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booker_timezone",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Booker Timezone"
            ),
        ),
    ]
