# Generated by Django 6.0.4 on 2026-05-18 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingIntegrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('access_type', models.CharField(choices=[('all', 'All Users'), ('roles', 'Specific Roles'), ('users', 'Specific Users')], default='all', help_text='Who can generate meeting links.', max_length=10, verbose_name='Access Type')),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='meeting_integrations', to='core.role', verbose_name='Allowed Roles')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='meeting_integrations', to=settings.AUTH_USER_MODEL, verbose_name='Allowed Users')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Meeting Integration Setting',
                'verbose_name_plural': 'Meeting Integration Settings',
            },
        ),
        migrations.CreateModel(
            name='MeetingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('ms_teams', 'Microsoft Teams')], max_length=30, verbose_name='Provider')),
                ('title', models.CharField(max_length=255, verbose_name='Meeting Title')),
                ('meeting_url', models.URLField(max_length=2000, verbose_name='Meeting URL')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Start Date & Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date & Time')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_links', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Meeting Link',
                'verbose_name_plural': 'Meeting Links',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MicrosoftTeamsOAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID (Application ID)')),
                ('client_secret', models.CharField(blank=True, max_length=255, verbose_name='Client Secret')),
                ('tenant_id', models.CharField(blank=True, help_text="Your Azure AD tenant ID, or 'common' for multi-tenant apps.", max_length=255, verbose_name='Tenant ID')),
                ('token', models.JSONField(blank=True, default=dict, verbose_name='OAuth Token')),
                ('oauth_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='OAuth State')),
                ('connected_email', models.EmailField(blank=True, max_length=254, verbose_name='Connected Account Email')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teams_oauth_config', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Microsoft Teams OAuth Config',
                'verbose_name_plural': 'Microsoft Teams OAuth Configs',
            },
        ),
        migrations.CreateModel(
            name='ZoomOAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, verbose_name='Client Secret')),
                ('token', models.JSONField(blank=True, default=dict, verbose_name='OAuth Token')),
                ('oauth_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='OAuth State')),
                ('connected_email', models.EmailField(blank=True, max_length=254, verbose_name='Connected Account Email')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_oauth_config', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Zoom OAuth Config',
                'verbose_name_plural': 'Zoom OAuth Configs',
            },
        ),
        migrations.CreateModel(
            name='UserMeetingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('ms_teams', 'Microsoft Teams')], max_length=30, verbose_name='Provider')),
                ('personal_meeting_url', models.URLField(blank=True, help_text='Your static personal meeting room link, if available.', max_length=1000, verbose_name='Personal Meeting URL')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_configs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Meeting Config',
                'verbose_name_plural': 'User Meeting Configs',
                'unique_together': {('user', 'provider', 'company')},
            },
        ),
    ]
