# Generated by Django 6.0.4 on 2026-05-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingLink',
        ),
    ]
