"""URL configuration for opportunities module."""

# First party imports (Horilla)
from horilla.urls import path

# Local imports
from horilla_crm.opportunities import views

app_name = "opportunities"

urlpatterns = [
    path(
        "opportunities-view/",
        views.OpportunityView.as_view(),
        name="opportunities_view",
    ),
    path(
        "opportunities-nav/",
        views.OpportunityNavbar.as_view(),
        name="opportunities_nav",
    ),
    path(
        "opportunities-list/",
        views.OpportunityListView.as_view(),
        name="opportunities_list",
    ),
    path(
        "opportunities-kanban/",
        views.OpportunityKanbanView.as_view(),
        name="opportunities_kanban",
    ),
    path(
        "opportunities-card/",
        views.OpportunityCardView.as_view(),
        name="opportunities_card",
    ),
    path(
        "opportunities-group-by/",
        views.OpportunityGroupByView.as_view(),
        name="opportunities_group_by",
    ),
    path(
        "opportunities-layout-split/",
        views.OpportunitySplitView.as_view(),
        name="opportunities_split_view",
    ),
    path(
        "opportunities-chart/",
        views.OpportunityChartView.as_view(),
        name="opportunities_chart",
    ),
    path(
        "opportunities-timeline/",
        views.OpportunityTimelineView.as_view(),
        name="opportunities_timeline",
    ),
    path(
        "opportunity-create/",
        views.OpportunityMultiStepFormView.as_view(),
        name="opportunity_create",
    ),
    path(
        "opportunity-single-create/",
        views.OpportunitySingleFormView.as_view(),
        name="opportunity_single_create",
    ),
    path(
        "related-contact-opportunity-create/",
        views.RelatedOpportunityFormView.as_view(),
        name="related_contact_opportunity_create",
    ),
    path(
        "opportunity-edit/<int:pk>/",
        views.OpportunityMultiStepFormView.as_view(),
        name="opportunity_edit",
    ),
    path(
        "opportunity-single-edit/<int:pk>/",
        views.OpportunitySingleFormView.as_view(),
        name="opportunity_single_edit",
    ),
    path(
        "opportunity-delete/<int:pk>/",
        views.OpportunityDeleteView.as_view(),
        name="opportunity_delete",
    ),
    path(
        "opportunity-contact-role-delete/<int:pk>/",
        views.OpportunityContactRoleDeleteView.as_view(),
        name="opportunity_contact_role_delete",
    ),
    path(
        "opportunity-change-owner/<int:pk>/",
        views.OpportunityChangeOwnerForm.as_view(),
        name="opportunity_change_owner",
    ),
    path(
        "opportunity-detail-view/<int:pk>/",
        views.OpportunityDetailView.as_view(),
        name="opportunity_detail_view",
    ),
    path(
        "opportunity-detail-view-tabs/",
        views.OpportunityDetailViewTabView.as_view(),
        name="opportunity_detail_view_tabs",
    ),
    path(
        "opportunity-details-tab/<int:pk>/",
        views.OpportunityDetailTab.as_view(),
        name="opportunity_details_tab",
    ),
    path(
        "opportunity-activity-detail-view/<int:pk>/",
        views.OpportunityActivityTabView.as_view(),
        name="opportunity_activity_detail_view",
    ),
    path(
        "opportunity-notes-attachments/<int:pk>/",
        views.OpportunitiesNotesAndAttachments.as_view(),
        name="opportunity_notes_attachments",
    ),
    path(
        "opportunity-related-lists/<int:pk>/",
        views.OpportunityRelatedLists.as_view(),
        name="opportunity_related_lists",
    ),
    path(
        "opportunity-history-tab-view/<int:pk>/",
        views.OpportunityHistoryTabView.as_view(),
        name="opportunity_history_tab_view",
    ),
    path(
        "add-opportunity-contact-role/",
        views.OpportunityContactRoleFormview.as_view(),
        name="add_opportunity_contact_role",
    ),
    path(
        "edit-opportunity-contact-role/<int:pk>/",
        views.OpportunityContactRoleFormview.as_view(),
        name="edit_opportunity_contact_role",
    ),
    # opportunity stage urls
    path(
        "opportunity-stage-view/",
        views.OpportunityStageView.as_view(),
        name="opportunity_stage_view",
    ),
    path(
        "opportunity-stage-nav-view/",
        views.OpportunityStageNavbar.as_view(),
        name="opportunity_stage_nav_view",
    ),
    path(
        "opportunity-stage-list-view/",
        views.OpportunityStageListView.as_view(),
        name="opportunity_stage_list_view",
    ),
    path(
        "change-opportunity-stage-final/<int:pk>/",
        views.ChangeFinalStage.as_view(),
        name="change_opportunity_stage_final",
    ),
    path(
        "edit-opportunity-stage/<int:pk>/",
        views.CreateOpportunityStage.as_view(),
        name="edit_opportunity_stage",
    ),
    path(
        "create-opportunity-stage/",
        views.CreateOpportunityStage.as_view(),
        name="create_opportunity_stage",
    ),
    path(
        "toggle-order-field/",
        views.OpportynityToggleOrderFieldView.as_view(),
        name="toggle_order_field",
    ),
    path(
        "delete-opportunity-stage/<int:pk>/",
        views.OpportunityStatusDeleteView.as_view(),
        name="delete_opportunity_stage",
    ),
    path(
        "update-opportunity-stage-order/",
        views.UpdateOpportunityStageOrderView.as_view(),
        name="update_opportunity_stage_order",
    ),
    path(
        "company/<int:company_id>/load-opp-stages/",
        views.LoadOpportunityStagesView.as_view(),
        name="load_opp_stages",
    ),
    path(
        "company/<int:pk>/create-opp-stage-group/",
        views.CreateOppStageGroupView.as_view(),
        name="create_opp_stage_group",
    ),
    path(
        "company/<int:company_id>/custom-opp-stages-form/",
        views.CustomOppStagesFormView.as_view(),
        name="custom_opp_stage_form",
    ),
    path(
        "company/<int:company_id>/save-custom-opp-stages/",
        views.SaveCustomOppStagesView.as_view(),
        name="save_custom_opp_stages",
    ),
    # Big deal alert urls
    path(
        "big-deal-alert-view/",
        views.BigDealAlertView.as_view(),
        name="big_deal_alert_view",
    ),
    path(
        "big-deal-alert-nav/",
        views.BigDealAlertNavbar.as_view(),
        name="big_deal_alert_nav",
    ),
    path(
        "big-deal-alert-list/",
        views.BigDealAlertListView.as_view(),
        name="big_deal_alert_list",
    ),
    path(
        "big-deal-automation-create/",
        views.BigDealAutomationFormView.as_view(),
        name="big_deal_automation_create",
    ),
    path(
        "big-deal-automation-update/<int:pk>/",
        views.BigDealAutomationFormView.as_view(),
        name="big_deal_automation_update",
    ),
    # opportunity team urls
    path(
        "opportunity-team-view/",
        views.OpportunityTeamView.as_view(),
        name="opportunity_team_view",
    ),
    path(
        "opportunity-team-nav-view/",
        views.OpportunityTeamNavbar.as_view(),
        name="opportunity_team_nav_view",
    ),
    path(
        "opportunity-team-list-view/",
        views.OpportunityTeamListView.as_view(),
        name="opportunity_team_list_view",
    ),
    path(
        "edit-opportunity-team/<int:pk>/",
        views.OpportunityTeamFormView.as_view(),
        name="edit_opportunity_team",
    ),
    path(
        "create-opportunity-team/",
        views.OpportunityTeamFormView.as_view(),
        name="create_opportunity_team",
    ),
    path(
        "opportunity-team-detail-view/<int:pk>/",
        views.OpportunityTeamDetailView.as_view(),
        name="opportunity_team_detail_view",
    ),
    path(
        "opportunity-team-detail-nav-view/",
        views.OpportunityTeamDetailNavbar.as_view(),
        name="opportunity_team_detail_nav_view",
    ),
    path(
        "opportunity-team-detail-list-view/",
        views.OpportunityTeamDetailListView.as_view(),
        name="opportunity_team_detail_list_view",
    ),
    path(
        "create-opportunity-team-member/",
        views.OpportunityTeamMemberCreateView.as_view(),
        name="create_opportunity_team_member",
    ),
    path(
        "add-opportunity-member/",
        views.AddOpportunityMemberView.as_view(),
        name="add_opportunity_member",
    ),
    path(
        "edit-opportunity-team-member/<int:pk>/",
        views.OpportunityTeamMemberUpdateView.as_view(),
        name="edit_opportunity_team_member",
    ),
    path(
        "edit-opportunity-member/<int:pk>/",
        views.OpportunityMemberUpdateView.as_view(),
        name="edit_opportunity_member",
    ),
    path(
        "delete-opportunity-team/<int:pk>/",
        views.OpportunityTeamDeleteView.as_view(),
        name="delete_opportunity_team",
    ),
    path(
        "delete-opportunity-team-member/<int:pk>/",
        views.OpportunityTeamMembersDeleteView.as_view(),
        name="delete_opportunity_team_member",
    ),
    path(
        "delete-opportunity-member/<int:pk>/",
        views.OpportunityMembersDeleteView.as_view(),
        name="delete_opportunity_member",
    ),
    path(
        "team-selling/",
        views.TeamSellingSetupView.as_view(),
        name="team_selling_setup",
    ),
    path(
        "opportunity-split-view/",
        views.SplitTypeView.as_view(),
        name="opportunity_split_view",
    ),
    path(
        "opportunity-split-nav/",
        views.OpportunitySplitNavbar.as_view(),
        name="opportunity_split_nav",
    ),
    path(
        "opportunity-split-list/",
        views.OpportunitySplitListView.as_view(),
        name="opportunity_split_list",
    ),
    path(
        "opportunity-split-toggle/",
        views.ToggleOpportunitySplitView.as_view(),
        name="toggle_opportunit_split",
    ),
    path(
        "toggle-allow-all-users-split/",
        views.ToggleAllowAllUsersSplitView.as_view(),
        name="toggle_allow_all_users_split",
    ),
    path(
        "split-type-is-active/<int:pk>/",
        views.OpportunitySplitTypeActiveToggleView.as_view(),
        name="opportunity_split_toggle_active",
    ),
    path(
        "manage-opportunity-splits/",
        views.ManageOpportunitySplit.as_view(),
        name="manage_opportunity_splits",
    ),
    path(
        "opportunity-splits/",
        views.OpportunitySplitTabView.as_view(),
        name="opportunity_splits",
    ),
    path(
        "opportunity-splits-type-tab/<int:opportunity_id>/<int:split_type_id>/",
        views.OpportunitySplitTabContentView.as_view(),
        name="opportunity_split_tab_content",
    ),
    path(
        "save-opportunity-splits/<int:opportunity_id>/<int:split_type_id>/",
        views.SaveOpportunitySplitsView.as_view(),
        name="save_opportunity_splits",
    ),
    path(
        "opportunity-splits-add-row/<int:opportunity_id>/<int:split_type_id>/",
        views.AddSplitRowView.as_view(),
        name="add_split_row",
    ),
    path(
        "splits-delete/<int:split_id>/",
        views.DeleteSplitRowView.as_view(),
        name="delete_split_row",
    ),
    path(
        "opportunity-recalculate/<int:opportunity_id>/<int:split_type_id>/",
        views.RecalculateTotalsView.as_view(),
        name="recalculate_split_totals",
    ),
    path(
        "recalculate-row/<int:opportunity_id>/splits/<int:split_type_id>/",
        views.RecalculateSplitRowView.as_view(),
        name="recalculate_split_row",
    ),
    path(
        "team-selling/toggle/",
        views.ToggleTeamSellingView.as_view(),
        name="toggle_team_selling",
    ),
    path(
        "initialiaze-opportunity-stages/",
        views.InitializeDatabaseOpportunityStages.as_view(),
        name="initialiaze_opportunity_stages",
    ),
    path(
        "add-default-team/",
        views.AddDefaultTeamView.as_view(),
        name="add_default_team",
    ),
    path(
        "select-closed-stage/<int:pk>/",
        views.SelectClosedStageView.as_view(),
        name="select_closed_stage",
    ),
]
