# Generated by Django 6.0.4 on 2026-06-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0002_horillamail_bounced_at_horillamail_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="horillamail",
            name="rendered_body",
            field=models.TextField(
                blank=True, help_text="Rendered body saved at send time.", null=True
            ),
        ),
        migrations.AddField(
            model_name="horillamail",
            name="rendered_subject",
            field=models.CharField(
                blank=True,
                help_text="Rendered subject saved at send time.",
                max_length=255,
                null=True,
            ),
        ),
    ]
