# Generated by Django 6.0.4 on 2026-05-11 07:19

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToLeadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('accept_emails_from', models.TextField(blank=True, help_text='Comma-separated list of allowed sender email addresses. Leave blank to accept all.', null=True, verbose_name='Accept Emails From')),
                ('keywords', models.TextField(help_text='Comma-separated keywords to filter emails. Email must contain at least one keyword in subject OR body.', verbose_name='Keywords')),
                ('last_fetched', models.DateTimeField(blank=True, null=True, verbose_name='Last Fetched On')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lead Owner')),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.horillamailconfiguration', verbose_name='Incoming Mail')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Mail to Lead Config',
                'verbose_name_plural': 'Mail to Lead Config',
            },
        ),
        migrations.CreateModel(
            name='LeadCaptureForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('form_name', models.CharField(max_length=255, verbose_name='Form Name')),
                ('selected_fields', models.TextField(verbose_name='Selected Fields')),
                ('return_url_enable', models.BooleanField(default=False, verbose_name='Enable Return URL')),
                ('return_url', models.URLField(blank=True, null=True, verbose_name='Return URL')),
                ('success_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Success Message')),
                ('success_description', models.TextField(blank=True, null=True, verbose_name='Success Description')),
                ('enable_recaptcha', models.BooleanField(default=False, verbose_name='Enable Recaptcha')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('de', 'German'), ('fr', 'French')], default='en', max_length=10, verbose_name='Language')),
                ('header_color', models.CharField(max_length=7, verbose_name='Header Color')),
                ('generated_html', models.TextField(blank=True, null=True, verbose_name='Generated HTML')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_capture_forms', to=settings.AUTH_USER_MODEL, verbose_name='Lead Owner')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Lead Capture Form',
                'verbose_name_plural': 'Lead Capture Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Status Name')),
                ('order', models.IntegerField(default=0, verbose_name='Status Order')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, help_text='Leave blank for default (primary theme colour).', image_field=None, max_length=25, null=True, samples=None, verbose_name='Status Color')),
                ('is_final', models.BooleanField(default=False, verbose_name='Is Final Stage')),
                ('probability', models.DecimalField(decimal_places=2, help_text='Default probability percentage for this stage', max_digits=5, verbose_name='Probability')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Lead Stage',
                'verbose_name_plural': 'Lead Stages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('contact_number', models.CharField(blank=True, max_length=100, verbose_name='Contact Number')),
                ('fax', models.CharField(blank=True, max_length=100, verbose_name='Fax')),
                ('lead_source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('event', 'Event'), ('campaign', 'Campaign'), ('phone', 'Phone'), ('email', 'Email'), ('social_media', 'Social Media'), ('partner', 'Partner'), ('other', 'Other')], max_length=100, verbose_name='Lead Source')),
                ('lead_company', models.CharField(max_length=100, verbose_name='Company')),
                ('no_of_employees', models.IntegerField(blank=True, null=True, verbose_name='Total Employees')),
                ('industry', models.CharField(choices=[('finance', 'Finance'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('agriculture', 'Agriculture'), ('construction', 'Construction'), ('banking', 'Banking'), ('education', 'Education'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=100, verbose_name='Industry')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Annual Revenue')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('zip_code', models.CharField(blank=True, max_length=100, verbose_name='Zip')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Requirements')),
                ('is_convert', models.BooleanField(blank=True, default=False, editable=False, null=True)),
                ('lead_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Lead Score')),
                ('message_id', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead_owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='lead', to=settings.AUTH_USER_MODEL, verbose_name='Lead Owner')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('lead_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead', to='leads.leadstatus', verbose_name='Lead Stage')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
        # Scoring models moved to horilla_crm.scoring_rules app — managed by scoring_rules/migrations/0001_initial.py
        # migrations.CreateModel(
        #     name='ScoringCriterion',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
        #         ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
        #         ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
        #         ('name', models.CharField(blank=True, max_length=200, verbose_name='Criterion Name')),
        #         ('points', models.IntegerField(verbose_name='Points to Award')),
        #         ('operation_type', models.CharField(choices=[('add', 'Add'), ('sub', 'Sub')], default='and', max_length=3, verbose_name='Operation Type')),
        #         ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
        #         ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
        #         ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
        #         ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
        #     ],
        #     options={
        #         'verbose_name': 'Scoring Criterion',
        #         'verbose_name_plural': 'Scoring Criteria',
        #         'ordering': ['order', 'id'],
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ScoringCondition',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
        #         ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
        #         ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
        #         ('field', models.CharField(max_length=100, verbose_name='Field Name')),
        #         ('operator', models.CharField(choices=[('exact', 'Equals'), ('ne', 'Not Equals'), ('icontains', 'Contains'), ('not_contains', 'Does Not Contain'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('isnull', 'Is Empty'), ('isnotnull', 'Is Not Empty'), ('between', 'Between')], max_length=50, verbose_name='Operator')),
        #         ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
        #         ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3, verbose_name='Logical Operator')),
        #         ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
        #         ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
        #         ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
        #         ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
        #         ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='leads.scoringcriterion')),
        #     ],
        #     options={
        #         'verbose_name': 'Scoring Condition',
        #         'verbose_name_plural': 'Scoring Conditions',
        #         'ordering': ['order', 'id'],
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ScoringRule',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
        #         ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
        #         ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
        #         ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
        #         ('module', models.CharField(choices=[('lead', 'Lead'), ('opportunity', 'Opportunity'), ('account', 'Account'), ('contact', 'Contact')], max_length=50, verbose_name='Module')),
        #         ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
        #         ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
        #         ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
        #         ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
        #     ],
        #     options={
        #         'verbose_name': 'Scoring Rule',
        #         'verbose_name_plural': 'Scoring Rules',
        #     },
        # ),
        # migrations.AddField(
        #     model_name='scoringcriterion',
        #     name='rule',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='leads.scoringrule'),
        # ),
        # migrations.CreateModel(
        #     name='EmailActivityScoring',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
        #         ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
        #         ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
        #         ('activity_type', models.CharField(choices=[('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced')], max_length=50)),
        #         ('points', models.IntegerField(default=10)),
        #         ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
        #         ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
        #         ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
        #         ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_activities', to='leads.scoringrule')),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
    ]
