"""
Django settings for horilla project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# -----------------------------------------------------------------------------
#   Environment & Configuration Management
# -----------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent.parent
BASE_APP_DIR = BASE_DIR / "horilla"


# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, True),
    ENVIRONMENT=(str, "development"),  # production/staging/development
    SECRET_KEY=(str, "django-insecure-default-key"),
    ALLOWED_HOSTS=(list, ["*"]),
    CSRF_TRUSTED_ORIGINS=(list, ["http://localhost:8000"]),
    SITE_URL=(str, ""),
)

# Read from .env file if exists
env_file = BASE_DIR / ".env"
if env_file.exists():
    env.read_env(str(env_file), overwrite=True)

# Environment variables
DEBUG = env("DEBUG")
ENVIRONMENT = env("ENVIRONMENT")
SECRET_KEY = env("SECRET_KEY")
ALLOWED_HOSTS = env("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")
# Custom page when CSRF verification fails (production); DEBUG=True still uses Django's technical view.
CSRF_FAILURE_VIEW = "horilla.contrib.core.views.error_pages.csrf_failure"
# Public-facing HTTPS URL for Google Calendar webhook push notifications.
SITE_URL = env("SITE_URL")

# -----------------------------------------------------------------------------
#  Installed Apps Organization
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Core Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    # Daphne must come before staticfiles
    "daphne",
    # Core Django static app
    "django.contrib.staticfiles",
    # Third-party apps
    "channels",
    "whitenoise.runserver_nostatic",
    "colorfield",
    "djmoney",
    "django_filters",
    "django_summernote",
    "login_history",
    "auditlog",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_yasg",
    # Horilla apps
    "horilla.contrib.core",
    "horilla.contrib.generics",
    "horilla.contrib.reports",
    "horilla.contrib.dashboard",
    "horilla.contrib.utils",
    "horilla.contrib.notifications",
    "horilla.contrib.mail",
    "horilla.contrib.automations",
    "horilla.contrib.activity",
    "horilla.contrib.calendar",
    "horilla.contrib.keys",
    "horilla.contrib.theme",
    "horilla.contrib.duplicates",
    "horilla.contrib.process.approvals",
    "horilla.contrib.process.reviews",
    "horilla.contrib.cadences",
    "horilla.contrib.workflow",
    "horilla.contrib.meeting",
]


# -----------------------------------------------------------------------------
# REST Framework Configuration
# -----------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    # Rate limiting to mitigate resource starvation and DoS
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
}

# JWT Settings
SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Swagger/OpenAPI Settings
SWAGGER_SETTINGS = {
    "DEFAULT_AUTO_SCHEMA_CLASS": "horilla.api_urls.VerboseNameAutoSchema",
}

# -----------------------------------------------------------------------------
# Middleware Configuration
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "horilla.contrib.core.middlewares.TimezoneMiddleware",
    "horilla.contrib.core.middlewares.ActiveCompanyMiddleware",
    "horilla.contrib.core.middlewares.HorillaExceptionMiddleware",
    "horilla.contrib.core.middlewares.Horilla405Middleware",
    "horilla.contrib.core.middlewares.SVGSecurityMiddleware",
    "horilla.contrib.core.middlewares.HTMXRedirectMiddleware",
    "horilla.contrib.core.middlewares.EnsureSectionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "horilla.contrib.utils.middlewares.ThreadLocalMiddleware",
]


ROOT_URLCONF = "horilla.urls.project"

CONTEXT_PROCESSORS = [
    "django.template.context_processors.request",
    "django.contrib.auth.context_processors.auth",
    "django.contrib.messages.context_processors.messages",
    "horilla.context_processors.company_list",
    "horilla.context_processors.allowed_languages",
    "horilla.context_processors.recently_viewed_items",
    "horilla.context_processors.unread_notifications",
    "horilla.context_processors.menu_context_processor",
    "horilla.context_processors.currency_context",
    "horilla.context_processors.branding",
]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": CONTEXT_PROCESSORS,
            "builtins": [
                "django.templatetags.static",
                "django.templatetags.i18n",
                "horilla.contrib.generics.templatetags.horilla_tags",
            ],
        },
    },
]

WSGI_APPLICATION = "horilla.wsgi.application"
ASGI_APPLICATION = "horilla.asgi.application"


# -----------------------------------------------------------------------------
# Channels
# -----------------------------------------------------------------------------
CHANNEL_LAYERS = {
    "default": {
        # "BACKEND": "channels.layers.InMemoryChannelLayer",
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {
        #     "hosts": [("127.0.0.1", 6379)],  # Redis server
        # },
    },
}


# -----------------------------------------------------------------------------
# Database and Performance Enhancements
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# -----------------------------------------------------------------------------
if env("DATABASE_URL", default=None):
    DATABASES = {
        "default": env.db(),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": env("DB_ENGINE", default="django.db.backends.sqlite3"),
            "NAME": env(
                "DB_NAME",
                default=os.path.join(BASE_DIR, "db.sqlite3"),
            ),
            "USER": env("DB_USER", default=""),
            "PASSWORD": env("DB_PASSWORD", default=""),
            "HOST": env("DB_HOST", default=""),
            "PORT": env("DB_PORT", default=""),
        }
    }

# Connection persistence for better performance
DATABASES["default"]["CONN_MAX_AGE"] = env.int("DB_CONN_MAX_AGE", default=60)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGES = [
    ("af", "Afrikaans"),
    ("ar", "Arabic"),
    ("ast", "Asturian"),
    ("az", "Azerbaijani"),
    ("bg", "Bulgarian"),
    ("be", "Belarusian"),
    ("bn", "Bengali"),
    ("br", "Breton"),
    ("bs", "Bosnian"),
    ("ca", "Catalan"),
    ("ckb", "Central Kurdish (Sorani)"),
    ("cs", "Czech"),
    ("cy", "Welsh"),
    ("da", "Danish"),
    ("de", "German"),
    ("dsb", "Lower Sorbian"),
    ("el", "Greek"),
    ("en", "English"),
    ("en-au", "Australian English"),
    ("en-gb", "British English"),
    ("eo", "Esperanto"),
    ("es", "Spanish"),
    ("es-ar", "Spanish, Argentina"),
    ("es-co", "Spanish, Colombia"),
    ("es-mx", "Spanish, Mexico"),
    ("es-ni", "Spanish, Nicaragua"),
    ("es-ve", "Spanish, Venezuela"),
    ("et", "Estonian"),
    ("eu", "Basque"),
    ("fa", "Persian"),
    ("fi", "Finnish"),
    ("fr", "French"),
    ("fy", "Frisian"),
    ("ga", "Irish"),
    ("gd", "Scottish Gaelic"),
    ("gl", "Galician"),
    ("he", "Hebrew"),
    ("hi", "Hindi"),
    ("hr", "Croatian"),
    ("hsb", "Upper Sorbian"),
    ("hu", "Hungarian"),
    ("hy", "Armenian"),
    ("ia", "Interlingua"),
    ("id", "Indonesian"),
    ("ig", "Igbo"),
    ("io", "Ido"),
    ("is", "Icelandic"),
    ("it", "Italian"),
    ("ja", "Japanese"),
    ("ka", "Georgian"),
    ("kab", "Kabyle"),
    ("kk", "Kazakh"),
    ("km", "Khmer"),
    ("kn", "Kannada"),
    ("ko", "Korean"),
    ("ky", "Kyrgyz"),
    ("lb", "Luxembourgish"),
    ("lt", "Lithuanian"),
    ("lv", "Latvian"),
    ("mk", "Macedonian"),
    ("mn", "Mongolian"),
    ("mr", "Marathi"),
    ("ms", "Malay"),
    ("my", "Burmese"),
    ("nb", "Norwegian Bokmål"),
    ("ne", "Nepali"),
    ("nl", "Dutch"),
    ("nn", "Norwegian Nynorsk"),
    ("os", "Ossetian"),
    ("pa", "Punjabi"),
    ("pl", "Polish"),
    ("pt", "Portuguese"),
    ("pt-br", "Portuguese, Brazilian"),
    ("ro", "Romanian"),
    ("ru", "Russian"),
    ("sk", "Slovak"),
    ("sl", "Slovenian"),
    ("sq", "Albanian"),
    ("sr", "Serbian (Cyrillic)"),
    ("sr-latn", "Serbian (Latin)"),
    ("sv", "Swedish"),
    ("sw", "Swahili"),
    ("ta", "Tamil"),
    ("te", "Telugu"),
    ("tg", "Tajik"),
    ("th", "Thai"),
    ("tk", "Turkmen"),
    ("tr", "Turkish"),
    ("tt", "Tatar"),
    ("udm", "Udmurt"),
    ("uk", "Ukrainian"),
    ("ur", "Urdu"),
    ("uz", "Uzbek"),
    ("vi", "Vietnamese"),
    ("zh-hans", "Chinese Simplified"),
    ("zh-hant", "Chinese Traditional"),
]

# -----------------------------------------------------------------------------
# Localization
# -----------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
USE_I18N = True
USE_TZ = True
LOCALE_PATHS = [BASE_APP_DIR / "locale"]

# This will ignore browser language preferences
LANGUAGE_COOKIE_NAME = "django_language"
LANGUAGE_COOKIE_AGE = 31536000  # 1 year
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = "/"
LANGUAGE_COOKIE_SECURE = False
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_SAMESITE = "Lax"


# -----------------------------------------------------------------------------
# Authentication & Defaults
# -----------------------------------------------------------------------------
LOGIN_URL = "/login/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "core.HorillaUser"

# -----------------------------------------------------------------------------
# Email
# -----------------------------------------------------------------------------
EMAIL_BACKEND = "horilla.contrib.mail.backends.HorillaDefaultMailBackend"

DEFAULT_HOME_REDIRECT = "/dashboard/?section=home"

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

TIME_ZONE = "UTC"

AUDITLOG_INCLUDE_ALL_MODELS = True
AUDITLOG_EXCLUDE_TRACKING_MODELS = (
    "core.RecentlyViewed",
    "core.ActiveTab",
    "core.ListColumnVisibility",
)


try:
    from .password_utils import get_init_password

    DB_INIT_PASSWORD = get_init_password()
except ImportError as e:
    pass


ALLOWED_LANGUAGES = [
    ("en", "English", "usa.webp"),
    ("ar", "Arabic", "ar.png"),
    ("de", "German", "german.jpeg"),
    ("fr", "French", "france.webp"),
]

AUDITLOG_LOGENTRY_MODEL = "auditlog.LogEntry"

BRANDING_MODULE = None
