"""
URLs for the approvals app
"""

# First party imports (Horilla)
from horilla.urls import path

# Local imports
from . import views

app_name = "approvals"

urlpatterns = [
    path(
        "approval-process-view/",
        views.ApprovalProcessView.as_view(),
        name="approval_process_view",
    ),
    path(
        "approval-process-navbar-view/",
        views.ApprovalProcessNavbar.as_view(),
        name="approval_process_navbar_view",
    ),
    path(
        "approval-process-list-view/",
        views.ApprovalProcessListView.as_view(),
        name="approval_process_list_view",
    ),
    path(
        "approval-process-create-view/",
        views.ApprovalProcessCreateUpdateView.as_view(),
        name="approval_process_create_view",
    ),
    path(
        "approval-process-update-view/<int:pk>/",
        views.ApprovalProcessCreateUpdateView.as_view(),
        name="approval_process_update_view",
    ),
    path(
        "approval-process-delete-view/<int:pk>/",
        views.ApprovalProcessDeleteView.as_view(),
        name="approval_process_delete_view",
    ),
    path(
        "approval-process-toggle/<int:pk>/",
        views.ApprovalProcessToggleView.as_view(),
        name="approval_process_toggle_view",
    ),
    path(
        "approval-process-detail-view/<int:pk>/",
        views.ApprovalProcessDetailView.as_view(),
        name="approval_process_detail_view",
    ),
    path(
        "approval-process-detail-navbar-view/",
        views.ApprovalProcessDetailNavbar.as_view(),
        name="approval_process_detail_navbar_view",
    ),
    path(
        "approval-process-rule-create/<int:process_pk>/",
        views.ApprovalProcessRuleComposeView.as_view(),
        name="approval_process_rule_create_view",
    ),
    path(
        "approval-process-rule-update/<int:process_pk>/<int:pk>/",
        views.ApprovalProcessRuleComposeView.as_view(),
        name="approval_process_rule_update_view",
    ),
    path(
        "approval-process-rule-compose-dynamic/<int:process_pk>/",
        views.ApprovalProcessRuleComposeDynamicView.as_view(),
        name="approval_process_rule_compose_dynamic_view",
    ),
    path(
        "approval-process-rule-action-form/",
        views.ApprovalProcessRuleActionFormView.as_view(),
        name="approval_process_rule_action_form_view",
    ),
    path(
        "approval-process-rule-action-value-widget/",
        views.ApprovalProcessRuleActionValueWidgetView.as_view(),
        name="approval_process_rule_action_value_widget_view",
    ),
    path(
        "approval-process-rule-record-fields-fragment/",
        views.ApprovalProcessRuleRecordFieldsFragmentView.as_view(),
        name="approval_process_rule_record_fields_fragment_view",
    ),
    path(
        "approval-process-rule-delete-view/<int:pk>/",
        views.ApprovalProcessRuleDeleteView.as_view(),
        name="approval_process_rule_delete_view",
    ),
    path(
        "approval-process-rule-criteria/<int:pk>/",
        views.ApprovalProcessRuleCriteriaView.as_view(),
        name="approval_process_rule_criteria_view",
    ),
    path(
        "approval-jobs/",
        views.ApprovalJobView.as_view(),
        name="approval_job_view",
    ),
    path(
        "approval-jobs-navbar/",
        views.ApprovalJobNavbar.as_view(),
        name="approval_job_navbar_view",
    ),
    path(
        "approval-jobs-list/",
        views.ApprovalJobListView.as_view(),
        name="approval_job_list_view",
    ),
    path(
        "approval-jobs-tab-view/",
        views.ApprovalJobsTabView.as_view(),
        name="approval_jobs_tab_view",
    ),
    path(
        "approval-jobs-review/<int:pk>/",
        views.ApprovalJobReviewView.as_view(),
        name="approval_job_review_view",
    ),
    path(
        "approval-jobs-detail-tabs/<int:pk>/",
        views.ApprovalJobDetailTabView.as_view(),
        name="approval_job_detail_tab_view",
    ),
    path(
        "approval-jobs-detail-tab-details/",
        views.ApprovalJobDetailDetailsTabView.as_view(),
        name="approval_job_detail_details_tab_view",
    ),
    path(
        "approval-jobs-detail-tab-timeline/",
        views.ApprovalJobDetailTimelineTabView.as_view(),
        name="approval_job_detail_timeline_tab_view",
    ),
    path(
        "approval-jobs-detail-tab-tasks/",
        views.ApprovalJobDetailTasksTabView.as_view(),
        name="approval_job_detail_tasks_tab_view",
    ),
    path(
        "approval-jobs-respond-modal/<int:pk>/",
        views.ApprovalJobRespondModalView.as_view(),
        name="approval_job_respond_modal_view",
    ),
    path(
        "approval-jobs-field-update/<int:pk>/",
        views.ApprovalJobFieldUpdateView.as_view(),
        name="approval_job_field_update_view",
    ),
    path(
        "approval-history-navbar/",
        views.ApprovalHistoryNavbar.as_view(),
        name="approval_history_navbar_view",
    ),
    path(
        "approval-history-list/",
        views.ApprovalHistoryListView.as_view(),
        name="approval_history_list_view",
    ),
    path(
        "approval-history-delete/<int:pk>/",
        views.ApprovalHistoryDeleteView.as_view(),
        name="approval_history_delete_view",
    ),
    path(
        "approval-history-detail/<int:pk>/",
        views.ApprovalHistoryDetailView.as_view(),
        name="approval_history_detail_view",
    ),
    path(
        "approval-history-detail-tabs/<int:pk>/",
        views.ApprovalHistoryDetailTabView.as_view(),
        name="approval_history_detail_tab_view",
    ),
    path(
        "approval-history-detail-tab-details/",
        views.ApprovalHistoryDetailDetailsTabView.as_view(),
        name="approval_history_detail_details_tab_view",
    ),
    path(
        "approval-history-detail-tab-timeline/",
        views.ApprovalHistoryDetailTimelineTabView.as_view(),
        name="approval_history_detail_timeline_tab_view",
    ),
    path(
        "approval-history-detail-tab-tasks/",
        views.ApprovalHistoryDetailTasksTabView.as_view(),
        name="approval_history_detail_tasks_tab_view",
    ),
    path(
        "approval-history-resubmit/<int:pk>/",
        views.ApprovalHistoryResubmitView.as_view(),
        name="approval_history_resubmit_view",
    ),
    path(
        "approval-history-task-status-update/<int:pk>/",
        views.ApprovalHistoryTaskStatusUpdateView.as_view(),
        name="approval_history_task_status_update_view",
    ),
]
