# Generated by Django 6.0 on 2026-05-20 10:51

import django.db.models.deletion
import horilla.registry.limiters
from django.conf import settings
from django.db import migrations, models

# Models in the order they must be created on a fresh database (parents first,
# children later).
_MODELS_IN_CREATE_ORDER = [
    "ScoringRule",
    "ScoringCriterion",
    "ScoringCondition",
    "EmailActivityScoring",
]

# Existing client: rename these `leads_*` tables to `scoring_rules_*`.
_TABLE_RENAMES = [
    ("leads_scoringrule", "scoring_rules_scoringrule"),
    ("leads_scoringcriterion", "scoring_rules_scoringcriterion"),
    ("leads_scoringcondition", "scoring_rules_scoringcondition"),
    ("leads_emailactivityscoring", "scoring_rules_emailactivityscoring"),
]

# Existing client: old `ScoringRule.module` CharField values -> ContentType keys
_MODULE_VALUE_TO_CT = {
    "lead": ("leads", "lead"),
    "opportunity": ("opportunities", "opportunity"),
    "account": ("accounts", "account"),
    "contact": ("contacts", "contact"),
}

# Existing client: django_content_type rows whose app_label must move from
# `leads` to `scoring_rules` so permissions and GFKs continue resolving.
_MOVED_CT_MODELS = [
    "scoringrule",
    "scoringcriterion",
    "scoringcondition",
    "emailactivityscoring",
]


def _table_exists(schema_editor, table_name):
    return table_name in schema_editor.connection.introspection.table_names()


def _column_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor, table_name
        )
    return any(col.name == column_name for col in description)


def _migrate_existing_client(apps, schema_editor):
    """Rename leads_* tables, convert module column, and update content types."""
    connection = schema_editor.connection
    vendor = connection.vendor

    # 1. Rename leads_* -> scoring_rules_*
    for old, new in _TABLE_RENAMES:
        if _table_exists(schema_editor, old) and not _table_exists(schema_editor, new):
            schema_editor.execute(f'ALTER TABLE "{old}" RENAME TO "{new}";')

    # 2. Convert ScoringRule.module CharField -> ForeignKey
    rule_table = "scoring_rules_scoringrule"
    has_old_module = _column_exists(schema_editor, rule_table, "module")
    has_new_module = _column_exists(schema_editor, rule_table, "module_id")

    if has_old_module and not has_new_module:
        schema_editor.execute(
            f'ALTER TABLE "{rule_table}" ADD COLUMN "module_id" integer NULL;'
        )

        ContentType = apps.get_model("contenttypes", "ContentType")
        with connection.cursor() as cursor:
            for old_value, (app_label, model_name) in _MODULE_VALUE_TO_CT.items():
                ct = ContentType.objects.filter(
                    app_label=app_label, model=model_name
                ).first()
                if ct is None:
                    continue
                cursor.execute(
                    f'UPDATE "{rule_table}" SET "module_id" = %s WHERE "module" = %s;',
                    [ct.pk, old_value],
                )

            # Backfill unmapped rows with Lead CT so NOT NULL holds.
            default_ct = ContentType.objects.filter(
                app_label="leads", model="lead"
            ).first()
            if default_ct is not None:
                cursor.execute(
                    f'UPDATE "{rule_table}" SET "module_id" = %s '
                    f'WHERE "module_id" IS NULL;',
                    [default_ct.pk],
                )

        schema_editor.execute(f'ALTER TABLE "{rule_table}" DROP COLUMN "module";')

        if vendor == "postgresql":
            schema_editor.execute(
                f'ALTER TABLE "{rule_table}" ' f'ALTER COLUMN "module_id" SET NOT NULL;'
            )
            schema_editor.execute(
                f'ALTER TABLE "{rule_table}" '
                f'ADD CONSTRAINT "scoring_rules_scoringrule_module_id_fk_dct" '
                f'FOREIGN KEY ("module_id") REFERENCES "django_content_type" ("id") '
                f"DEFERRABLE INITIALLY DEFERRED;"
            )
            schema_editor.execute(
                f'CREATE INDEX "scoring_rules_scoringrule_module_id_idx" '
                f'ON "{rule_table}" ("module_id");'
            )
        # SQLite skips FK/NOT NULL — ALTER TABLE limitations; dev-only.

    # 3. Update django_content_type.app_label leads -> scoring_rules
    with connection.cursor() as cursor:
        for model_name in _MOVED_CT_MODELS:
            cursor.execute(
                'UPDATE "django_content_type" SET app_label = %s '
                "WHERE app_label = %s AND model = %s;",
                ["scoring_rules", "leads", model_name],
            )


def create_or_migrate(apps, schema_editor):
    """
    Single entry point handling both paths:

    - Existing client: leads_scoringrule exists  -> rename + convert + update CTs
    - New client:      no leads_* tables         -> create scoring_rules_* fresh
    - Already migrated (re-run): scoring_rules_* already exists -> no-op

    NOTE: We must use Django's *live* app registry (`django.apps.apps`), not
    the historical `apps` arg. SeparateDatabaseAndState passes the pre-state
    here, which doesn't yet contain the scoring_rules models — so
    `apps.get_model("scoring_rules", ...)` raises LookupError on fresh DBs.
    """
    if _table_exists(schema_editor, "leads_scoringrule"):
        _migrate_existing_client(apps, schema_editor)
        return

    if _table_exists(schema_editor, "scoring_rules_scoringrule"):
        return

    from django.apps import apps as live_apps

    for model_name in _MODELS_IN_CREATE_ORDER:
        model = live_apps.get_model("scoring_rules", model_name)
        schema_editor.create_model(model)


def drop_tables(apps, schema_editor):
    """Reverse path: drop the scoring_rules_* tables (best-effort)."""
    if not _table_exists(schema_editor, "scoring_rules_scoringrule"):
        return

    from django.apps import apps as live_apps

    for model_name in reversed(_MODELS_IN_CREATE_ORDER):
        model = live_apps.get_model("scoring_rules", model_name)
        schema_editor.delete_model(model)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_businesshour_options_businesshour_holidays_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_or_migrate, drop_tables),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ScoringCriterion",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(default=True, verbose_name="Is Active"),
                        ),
                        (
                            "additional_info",
                            models.JSONField(
                                blank=True, null=True, verbose_name="Additional info"
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True, verbose_name="Created At"
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(
                                auto_now=True, verbose_name="Updated At"
                            ),
                        ),
                        (
                            "name",
                            models.CharField(
                                blank=True,
                                max_length=200,
                                verbose_name="Criterion Name",
                            ),
                        ),
                        ("points", models.IntegerField(verbose_name="Points to Award")),
                        (
                            "operation_type",
                            models.CharField(
                                choices=[("add", "Add"), ("sub", "Sub")],
                                default="and",
                                max_length=3,
                                verbose_name="Operation Type",
                            ),
                        ),
                        (
                            "order",
                            models.PositiveIntegerField(
                                default=0, verbose_name="Order"
                            ),
                        ),
                        (
                            "company",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="core.company",
                                verbose_name="Company",
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_created",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Created By",
                            ),
                        ),
                        (
                            "updated_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_updated",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Updated By",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Scoring Criterion",
                        "verbose_name_plural": "Scoring Criteria",
                        "ordering": ["order", "id"],
                    },
                ),
                migrations.CreateModel(
                    name="ScoringCondition",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(default=True, verbose_name="Is Active"),
                        ),
                        (
                            "additional_info",
                            models.JSONField(
                                blank=True, null=True, verbose_name="Additional info"
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True, verbose_name="Created At"
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(
                                auto_now=True, verbose_name="Updated At"
                            ),
                        ),
                        (
                            "field",
                            models.CharField(max_length=100, verbose_name="Field Name"),
                        ),
                        (
                            "operator",
                            models.CharField(
                                choices=[
                                    ("exact", "Equals"),
                                    ("ne", "Not Equals"),
                                    ("icontains", "Contains"),
                                    ("not_contains", "Does Not Contain"),
                                    ("istartswith", "Starts With"),
                                    ("iendswith", "Ends With"),
                                    ("gt", "Greater Than"),
                                    ("gte", "Greater Than or Equal"),
                                    ("lt", "Less Than"),
                                    ("lte", "Less Than or Equal"),
                                    ("isnull", "Is Empty"),
                                    ("isnotnull", "Is Not Empty"),
                                    ("between", "Between"),
                                ],
                                max_length=50,
                                verbose_name="Operator",
                            ),
                        ),
                        (
                            "value",
                            models.CharField(
                                blank=True, max_length=255, verbose_name="Value"
                            ),
                        ),
                        (
                            "logical_operator",
                            models.CharField(
                                choices=[("and", "AND"), ("or", "OR")],
                                default="and",
                                max_length=3,
                                verbose_name="Logical Operator",
                            ),
                        ),
                        (
                            "order",
                            models.PositiveIntegerField(
                                default=0, verbose_name="Order"
                            ),
                        ),
                        (
                            "company",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="core.company",
                                verbose_name="Company",
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_created",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Created By",
                            ),
                        ),
                        (
                            "updated_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_updated",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Updated By",
                            ),
                        ),
                        (
                            "criterion",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="conditions",
                                to="scoring_rules.scoringcriterion",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Scoring Condition",
                        "verbose_name_plural": "Scoring Conditions",
                        "ordering": ["order", "id"],
                    },
                ),
                migrations.CreateModel(
                    name="ScoringRule",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(default=True, verbose_name="Is Active"),
                        ),
                        (
                            "additional_info",
                            models.JSONField(
                                blank=True, null=True, verbose_name="Additional info"
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True, verbose_name="Created At"
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(
                                auto_now=True, verbose_name="Updated At"
                            ),
                        ),
                        (
                            "name",
                            models.CharField(max_length=100, verbose_name="Rule Name"),
                        ),
                        (
                            "description",
                            models.TextField(
                                blank=True, null=True, verbose_name="Description"
                            ),
                        ),
                        (
                            "company",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="core.company",
                                verbose_name="Company",
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_created",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Created By",
                            ),
                        ),
                        (
                            "module",
                            models.ForeignKey(
                                limit_choices_to=horilla.registry.limiters.ContentTypeLimiter(
                                    "scoring_models"
                                ),
                                on_delete=django.db.models.deletion.PROTECT,
                                to="core.horillacontenttype",
                                verbose_name="Module",
                            ),
                        ),
                        (
                            "updated_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_updated",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Updated By",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Scoring Rule",
                        "verbose_name_plural": "Scoring Rules",
                    },
                ),
                migrations.AddField(
                    model_name="scoringcriterion",
                    name="rule",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="scoring_rules.scoringrule",
                    ),
                ),
                migrations.CreateModel(
                    name="EmailActivityScoring",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(default=True, verbose_name="Is Active"),
                        ),
                        (
                            "additional_info",
                            models.JSONField(
                                blank=True, null=True, verbose_name="Additional info"
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True, verbose_name="Created At"
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(
                                auto_now=True, verbose_name="Updated At"
                            ),
                        ),
                        (
                            "activity_type",
                            models.CharField(
                                choices=[
                                    ("opened", "Opened"),
                                    ("clicked", "Clicked"),
                                    ("bounced", "Bounced"),
                                ],
                                max_length=50,
                            ),
                        ),
                        ("points", models.IntegerField(default=10)),
                        (
                            "company",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="core.company",
                                verbose_name="Company",
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_created",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Created By",
                            ),
                        ),
                        (
                            "updated_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_updated",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Updated By",
                            ),
                        ),
                        (
                            "rule",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="email_activities",
                                to="scoring_rules.scoringrule",
                            ),
                        ),
                    ],
                    options={
                        "abstract": False,
                    },
                ),
            ],
        ),
    ]
